# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
        name: Compile site assets
        runs-on: self-hosted
        steps:
          - name: Docker Pull
            run: service docker start && docker pull express-gateway
    
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: express-gateaway
                options: -v ${{ github.workspace }}:/var/www
                run: |
                    composer install
                    npm install
                    npm run production
